#!/command/with-contenv sh
exec /usr/local/bin/barbacane serve \
  --artifact /etc/barbacane/burst-s3.bca \
  --listen 127.0.0.1:8081 \
  --admin-bind off \
  --allow-plaintext-upstream \
  --max-body-size 104857600
